// File: lib/data/mock_data.dart

import 'product_model.dart';
import 'shop_model.dart';

final List<Product> shopProducts = [
  Product(
    id: 'p1',
    name: 'iPhone 15 Pro Max',
    description:
        'أحدث هاتف من آبل بشريحة A17 Pro، كاميرا 48 ميجابكسل، وشاشة Dynamic Island',
    price: 55000.00,
    imageUrl:
        'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500&h=500&fit=crop',
    rating: 4.9,
    category: 'هواتف',
    brand: 'Apple',
    inStock: true,
    discount: 0.1,
    storage: '256 GB',
    color: 'تيتانيوم طبيعي',
    memory: '8 GB',
  ),
  Product(
    id: 'p2',
    name: 'Samsung Galaxy S24 Ultra',
    description:
        'هاتف أندرويد flagship بشريحة Snapdragon 8 Gen 3، قلم S-Pen، كاميرا 200 ميجابكسل',
    price: 48000.00,
    imageUrl:
        'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&h=500&fit=crop',
    rating: 4.7,
    category: 'هواتف',
    brand: 'Samsung',
    inStock: true,
    discount: 0.05,
    storage: '512 GB',
    color: 'أسود',
    memory: '12 GB',
  ),
  Product(
    id: 'p3',
    name: 'AirPods Pro 2',
    description:
        'سماعات لاسلكية مع إلغاء ضوضاء نشط، مقاومة للماء، بطارية 30 ساعة',
    price: 9000.00,
    imageUrl:
        'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=500&h=500&fit=crop',
    rating: 4.8,
    category: 'إكسسوارات',
    brand: 'Apple',
    inStock: true,
    discount: 0.0,
    storage: 'N/A',
    color: 'أبيض',
    memory: 'N/A',
  ),
  Product(
    id: 'p4',
    name: 'Xiaomi 14 Pro',
    description:
        'هاتف ذكي بكاميرات Leica، شاشة 120Hz، شريحة Snapdragon 8 Gen 3',
    price: 32000.00,
    imageUrl:
        'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=500&h=500&fit=crop',
    rating: 4.6,
    category: 'هواتف',
    brand: 'Xiaomi',
    inStock: true,
    discount: 0.15,
    storage: '256 GB',
    color: 'أخضر',
    memory: '12 GB',
  ),
  Product(
    id: 'p5',
    name: 'Samsung Galaxy Watch 6',
    description: 'ساعة ذكية مع مستشعرات صحية متقدمة، شاشة AMOLED، مقاومة للماء',
    price: 6500.00,
    imageUrl:
        'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=500&h=500&fit=crop',
    rating: 4.5,
    category: 'إكسسوارات',
    brand: 'Samsung',
    inStock: false,
    discount: 0.0,
    storage: '44mm',
    color: 'فضي',
    memory: '2 GB',
  ),
  Product(
    id: 'p6',
    name: 'Google Pixel 8 Pro',
    description: 'هاتف بكاميرات متطورة، شاشة 120Hz، معالج Tensor G3',
    price: 42000.00,
    imageUrl:
        'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=500&h=500&fit=crop',
    rating: 4.7,
    category: 'هواتف',
    brand: 'Google',
    inStock: true,
    discount: 0.08,
    storage: '128 GB',
    color: 'أسود',
    memory: '12 GB',
  ),
];

final List<Shop> availableShops = [
  Shop(
    id: 's1',
    name: 'إنسان الحياة',
    location: 'القاهرة - مدينة نصر',
    rating: 4.8,
    products: shopProducts,
    imageUrl:
        'https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?w=500&h=300&fit=crop',
    isVerified: true,
    isOpen: true,
    specialOffers: 'خصم 20% على الإكسسوارات',
    reviewCount: 1280,
    deliveryTime: '30-45 دقيقة',
    minOrder: 50.0,
    categories: ['هواتف', 'إكسسوارات', 'شاشات'],
  ),
  Shop(
    id: 's2',
    name: 'المحترف للإلكترونيات',
    location: 'الجيزة - الدقي',
    rating: 4.5,
    products: shopProducts.sublist(1, 4),
    imageUrl:
        'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=500&h=300&fit=crop',
    isVerified: true,
    isOpen: true,
    specialOffers: 'توصيل مجاني للطلبات فوق 500 جنيه',
    reviewCount: 890,
    deliveryTime: '45-60 دقيقة',
    minOrder: 100.0,
    categories: ['هواتف', 'تابلت'],
  ),
  Shop(
    id: 's3',
    name: 'تكنو ستور',
    location: 'القاهرة - المعادي',
    rating: 4.9,
    products: shopProducts.sublist(2, 5),
    imageUrl:
        'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=500&h=300&fit=crop',
    isVerified: true,
    isOpen: false,
    specialOffers: 'عرض التقسيط بدون مقدم',
    reviewCount: 2150,
    deliveryTime: '25-40 دقيقة',
    minOrder: 75.0,
    categories: ['هواتف', 'إكسسوارات', 'أجهزة لوحية'],
  ),
  Shop(
    id: 's4',
    name: 'ديجي مارت',
    location: 'القاهرة - مصر الجديدة',
    rating: 4.3,
    products: shopProducts.sublist(0, 3),
    imageUrl:
        'https://images.unsplash.com/photo-1563017306-c6b8e3f2c0c1?w=500&h=300&fit=crop',
    isVerified: false,
    isOpen: true,
    specialOffers: 'خصم 10% على أول طلب',
    reviewCount: 450,
    deliveryTime: '50-70 دقيقة',
    minOrder: 150.0,
    categories: ['هواتف', 'سماعات'],
  ),
  Shop(
    id: 's5',
    name: 'موبايل زون',
    location: 'الجيزة - المهندسين',
    rating: 4.7,
    products: shopProducts.sublist(3),
    imageUrl:
        'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=500&h=300&fit=crop',
    isVerified: true,
    isOpen: true,
    specialOffers: 'ضمان 3 سنوات على الهواتف',
    reviewCount: 1670,
    deliveryTime: '35-50 دقيقة',
    minOrder: 0.0,
    categories: ['هواتف', 'ساعات ذكية'],
  ),
];
